"""[3A] Manus Skeleton → dex_retargeting → DG5F joint angles.

Wrapper around the dex-retargeting library (DexPilot/Vector/Position
optimizers, AnyTeleop RSS 2023) that adapts it to the teleop_dev
HandRetargetBase interface.

Pipeline:
    HandData.skeleton (21, 7) MANO 21-node layout
    → extract xyz, shift to wrist origin
    → build optimizer-specific ref_value (vector / dexpilot / position)
    → SeqRetargeting.retarget(ref_value)
    → DG5F joint angles (20,) in radians

Usage:
    from sender.hand.gen3a_dex_retarget import DexRetargetWrapper
    rt = DexRetargetWrapper(hand_side="right")
    q = rt.retarget(skeleton=hand_data.skeleton)  # (21, 7) → (20,)
"""

import logging
import time
from pathlib import Path
from typing import Optional

import numpy as np

from sender.hand.core.retarget_base import HandRetargetBase
from sender.hand.core.dg5f_config import NUM_JOINTS

logger = logging.getLogger(__name__)


class DexRetargetWrapper(HandRetargetBase):
    """[3A] dex-retargeting wrapper for Manus skeleton → DG5F.

    Parameters
    ----------
    hand_side : str
        "left" or "right" (only "right" config currently provided).
    config_path : str or None
        Path to YAML config. If None, defaults to
        ``gen3a_dex_retarget/config/dg5f_{hand_side}_dexpilot.yml``.
        The YAML's ``urdf_path`` is resolved relative to the YAML file
        itself, so configs can ship with relative paths.
    """

    def __init__(self, hand_side: str = "right", config_path: Optional[str] = None):
        super().__init__(hand_side)

        # Default to dexpilot config in this package
        here = Path(__file__).parent
        if config_path is None:
            config_path = here / "config" / f"dg5f_{hand_side}_dexpilot.yml"
        config_path = Path(config_path).resolve()
        if not config_path.exists():
            raise FileNotFoundError(f"DexRetarget config not found: {config_path}")

        # dex-retargeting expects an absolute urdf_path. The shipped YAML uses
        # a relative one (just the filename), so patch it before loading.
        from dex_retargeting.retargeting_config import RetargetingConfig

        urdf_dir = config_path.parent
        # RetargetingConfig.set_default_urdf_dir() lets us point at the YAML's
        # own directory; library then resolves relative urdf_path against it.
        try:
            RetargetingConfig.set_default_urdf_dir(str(urdf_dir))
        except AttributeError:
            # Older library versions: fall back to in-place YAML rewrite
            pass

        cfg = RetargetingConfig.load_from_file(str(config_path))
        self._retargeting = cfg.build()

        # Single source of truth: the optimizer's own indices.
        # - vector:   (2, N) array from YAML target_link_human_indices
        # - dexpilot: (2, num_pairs + num_fingers) auto-generated by
        #             DexPilotOptimizer.__init__ via generate_link_indices()
        # - position: (N,) array of fingertip indices
        opt = self._retargeting.optimizer
        self._retargeting_type = opt.retargeting_type
        self._human_indices = opt.target_link_human_indices

        self._wrist_idx = 0  # MANO 21 wrist
        self._last_solve_ms = 0.0

        logger.info(
            "DexRetargetWrapper loaded (hand=%s, type=%s, config=%s, joints=%d)",
            hand_side,
            self._retargeting_type,
            config_path.name,
            len(self._retargeting.joint_names),
        )

    def retarget(self, skeleton: Optional[np.ndarray] = None, **kwargs) -> np.ndarray:
        """Manus skeleton (21, 7) → DG5F joint angles (20,).

        Parameters
        ----------
        skeleton : ndarray[21, 7] or None
            MANO 21-node array [x, y, z, qw, qx, qy, qz]. If None or wrong
            shape, returns the previous solution (warm-start hold).

        Returns
        -------
        ndarray[20] DG5F joint angles in radians (clamped by underlying
        SeqRetargeting to URDF joint limits).
        """
        if skeleton is None or skeleton.shape[0] < 21:
            return np.zeros(NUM_JOINTS, dtype=np.float32)

        # Extract xyz, shift to wrist origin (matches retarget_dev ManusSensing)
        kp = skeleton[:21, :3].astype(np.float32)
        kp = kp - kp[self._wrist_idx]

        ref_value = self._build_ref_value(kp)

        t0 = time.perf_counter()
        q = self._retargeting.retarget(ref_value)
        self._last_solve_ms = (time.perf_counter() - t0) * 1000

        return q.astype(np.float32)

    def get_method_name(self) -> str:
        return "3A-dex-retarget"

    def get_debug_info(self) -> Optional[dict]:
        return {
            "method": self.get_method_name(),
            "type": self._retargeting_type,
            "solve_time_ms": self._last_solve_ms,
        }

    def get_joint_names(self) -> list[str]:
        return list(self._retargeting.joint_names)

    @property
    def solve_time_ms(self) -> float:
        return self._last_solve_ms

    def _build_ref_value(self, kp: np.ndarray) -> np.ndarray:
        """Convert (21, 3) keypoints to optimizer-specific input.

        Mirrors retarget_dev/models/dex_retarget/dex_retarget_model.py — uses
        the optimizer's stored target_link_human_indices so vector and dexpilot
        share the exact same code path the library expects.
        """
        idx = self._human_indices
        if self._retargeting_type == "POSITION":
            return kp[idx, :]
        origin_indices = idx[0, :]
        task_indices = idx[1, :]
        return kp[task_indices, :] - kp[origin_indices, :]
